{
  "type": "record",
  "name": "FFViiAllyUpdate",
  "namespace": "com.bevans.avro.ffvii",
  "fields": [
    {
      "name": "name",
      "type": "string"
    },
    {
      "name": "age",
      "type": "int"
    },
    {
      "name": "exp",
      "type": "long"
    },
    {
      "name": "hp",
      "type": "int"
    },
    {
      "name": "mp",
      "type": "int"
    },
    {
      "name": "winLossRatio",
      "type": "float"
    },
    {
      "name": "psStoreCost",
      "type": "double"
    },
    {
      "name": "nameInBytes",
      "type": [
        "null",
        "bytes"
      ],
      "default": null
    },
    {
      "name": "weapon",
      "type": {
        "name": "FFViiAllyWeapon",
        "type": "record",
        "namespace": "com.bevans.avro.ffvii.weapon",
        "fields": [
          {
            "name": "name",
            "type": "string"
          },
          {
            "name": "attack",
            "type": "int"
          },
          {
            "name": "magicAttack",
            "type": "int"
          }
        ]
      }
    },
    {
      "name": "materia",
      "type": {
        "type": "array",
        "items": "string"
      }
    }
  ]
}
