plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'kafka-connect-stack'

include('connect-smt-lib')
include('connect-spring-boot-app')
include('jacoco-report-aggregation')
