plugins {
    id 'bevans.java-conventions'
    id 'java-library'
    id 'org.sonarqube' version '4.4.1.3373'
}

ext {
    connectVersion = '3.7.0'
    jsonVersion = '20240303'
}

dependencies {
    api("org.apache.kafka:connect-api:${connectVersion}")

    implementation("org.apache.kafka:connect-transforms:${connectVersion}")
    implementation("org.json:json:${jsonVersion}")
}

test {
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
    }
}
jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                counter = 'LINE'
                minimum = 0.9
            }
            limit {
                counter = 'BRANCH'
                minimum = 0.8
            }
        }
    }
}

sonar {
    properties {
        property "sonar.projectKey", "bazzani_kafka-connect-stack"
        property("sonar.organization", "bazzani-github")
        property "sonar.host.url", "https://sonarcloud.io"
        property("sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacoco/test/jacocoTestReport.xml")
        property("sonar.junit.reportPaths", "build/test-results/test")
    }
}

tasks.named('check') {
    dependsOn jacocoTestCoverageVerification
}
